### ISSUE TITLE
RSS feed for new additions

### ISSUE THREAD

**Issue by nicksherman** [PaiJi/NetNewsWire-themes-collection#13]
I love this project, thank you for making it! It'd be great (and would seem fitting) if the site had its own RSS feed for updates when new themes are added.

**Comment by PaiJi** [comment]
👋 Hi, I've managed to add a basic RSS support, please check it out and let me know what you think!

**Comment by nicksherman** [comment]
Wow, that was fast! I just added the feed to my subscriptions and it seems to work fine. Thank you!
